### ISSUE TITLE
Lib.Libevent/sample/test.k occurs error on Mini Konoha 0.3

### ISSUE THREAD

**Issue by tosnoz** [konoha-project/konoha3#387]
Lib.Libevent パッケージの sample/test.k を Mini Konoha 0.3 で実行すると、以下のようなエラーとなります。
# 参考までに stable ブランチベースでは動作しているスクリプトです。
- (warning) (Libevent_kick.k:32) $ is not available within the class clause
- (error) (Libevent_kick.k:44) Argument(5) No Type declaration
- (error) (test.k:62) syntax error: new
- (error) (test.k:50) undefined method: System.evutil_make_socket_nonblocking
- (error) (Libevent_kick.k:36) syntax error: new
- (error) (Libevent_kick.k:36) undefined name: evbase
- (error) (Libevent_kick.k:36) undefined typing: () 'new'
  RuntimeScriptException: SoftwareFault (error) (Libevent_kick.k:36) undefined name: evbase
  StackTrace
  [13](Libevent_kick.k:36) Event_base.new(this=(Event_base) &0x7f1120b5d240, )
  [8](test.k:66) NameSpace.main(this=(NameSpace) main, )

gdb で少し追いかけてみたのですが、 AST 周りっぽいような _気がする_ という程度までしか追えていません。

ひとまず、不具合報告です。

**Comment by imasahiro** [comment]
パッケージの名前とパッケージの初期化関数は一致する必要がありました。
masterブランチではパッケージの名前を変更したのですが、修正し忘れていたようです。

c225f60
